Migrate to new organization
kontent-ai/java-packages pull request #141
Opened 2022-09-26 15:41 UTC by Simply007

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2022-10-13 10:09 UTC, IvanKiral commented
DELIVERY SDK:
- [ ] There are some `Kontent` instead of `Kontent.ai` ( comment suggestions in at least Readme are coming later with full review)
- [ ] Missing Javadocs (AsyncCache, Delivery client) - add or maybe create Issue?
- [ ] Restructure folders -> sometimes it is hard to implementation of interface (optional, also candidate for new issue)
- [ ]  Code is mostly good from my perspective, some comments are coming with full review later

2022-10-17 07:13 UTC, IvanKiral commented
Delivery-sdk-generators:
- [ ] Code looks good, only there are some only Kontent mentions. Although there are only comments they can be changed with replace

2022-10-17 08:22 UTC, IvanKiral commented
sample-app-android:
- [ ] There is a Floating Action button registered in `ArticlesFragment.java` it is not visible in the app though.
- [ ] There are some not changed Kontent -> Kontent.ai

2022-10-17 08:47 UTC, IvanKiral commented
sample-app-spring-boot:
- [ ] Change fonts to work sans
- [ ] Article.html has twice <!DOCTYPE html>
- [ ] Date in articles has weird format
- [ ] Linked items in rich text element are not working.. In article `coffee berages explained` clicking on `so rich as today` should navigate us to the `which brewing fits you?` article

2022-10-17 09:41 UTC, IvanKiral commented
Parent:
- There is a kontent-delivery folder with only empty readme

2022-10-17 09:41 UTC, IvanKiral requested changes

2022-10-20 20:57 UTC, Simply007 commented
I haven's found any old MIT liense in java files.

2022-10-20 21:25 UTC, Simply007 commented
> DELIVERY SDK:
> 
> * [x]  There are some `Kontent` instead of `Kontent.ai` ( comment suggestions in at least Readme are coming later with full review)
> * [ ]  All .java files does not have updated MIT license on the top of the file
I haven't found any old licences
> * [ ]  Missing Javadocs (AsyncCache, Delivery client) - add or maybe create Issue?
Added for asynccache and delivery client - create issue for the rest
> * [ ]  Restructure folders -> sometimes it is hard to implementation of interface (optional, also candidate for new issue)
Create issue if you want to 
> * [x]   Code is mostly good from my perspective, some comments are coming with full review later

2022-10-20 21:27 UTC, Simply007 commented on delivery-sdk/src/main/java/kontent/ai/delivery/Asset.java
I would leave it this way - or create a separate issue if you like it more 👍🏼

2022-10-20 23:07 UTC, Simply007 commented
> sample-app-spring-boot:
> 
> * [x]  Change fonts to work sans
> * [ ]  Article.html has twice
I don't understand
> * [x]  Date in articles has weird format
> * [x]  Linked items in rich text element are not working.. In article `coffee berages explained` clicking on `so rich as today` should navigate us to the `which brewing fits you?` article

2022-10-24 07:49 UTC, IvanKiral approved these changes

2022-10-24 07:49 UTC, IvanKiral commented on delivery-sdk/src/main/java/kontent/ai/delivery/CacheManager.java
> +     * @param jsonNode the JsonNode created from the response from the Kontent.ai Deliver API.
Delivery

2022-10-24 07:49 UTC, IvanKiral commented on delivery-sdk/src/main/java/kontent/ai/delivery/CacheManager.java
>       * Cache a response from the KontentDelivery API.
kontent.ai delivery api

2022-10-24 12:42 UTC, IvanKiral approved these changes

2022-10-24 13:02 UTC, merged