Make projectID and preview API configurable
kontent-ai/java-packages pull request #145
Opened 2022-10-27 14:31 UTC by Simply007

### Motivation

Internal link: DEVREL-694

Make the project Id and preview API key configurable. Currently using getIntent.getStringExtra().

* In combination with appetize it can be configurable => check i.e. https://github.com/kontent-ai/safelife-appetize-iframe

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2022-11-14 08:19 UTC, IvanKiral requested changes

2022-11-14 08:20 UTC, IvanKiral commented
Requested changes: 
- [ ] Add how to use customProjectId to readme
- [ ] Consider if taking customProjectId is right
- [ ] Considre renaming `resetClient`

2022-11-23 08:02 UTC, Simply007 commented on sample-app-android/src/main/java/kontent/ai/delivery_android_sample/app/core/BaseActivity.java
> +        String customProjectId = getIntent().getStringExtra("KontentProjectId");
I wanted to use it in combination with appetize: https://docs.appetize.io/core-features/playback-options -> a will add section to README.

Default value is null if nothing is set -> hence cndition right under that.

2022-11-23 08:33 UTC, Simply007 commented on sample-app-android/src/main/java/kontent/ai/delivery_android_sample/data/source/DeliveryClientProvider.java
> +    private static DeliveryClient resetClient(String previewAPiKey) {
renamed

2022-11-23 08:34 UTC, Simply007 commented
> Requested changes:
> 
> * [x]  Add how to use customProjectId to readme
> * [ ]  Consider if current approach of customProjectId is right

I think the code is fine - it is a sample..

> * [x]  Considre renaming `resetClient`

2022-11-29 08:48 UTC, IvanKiral approved these changes

2022-11-29 08:48 UTC, IvanKiral commented on sample-app-android/README.md
> +If you want to then use the Appetize you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to use unpublished content) like this:
I would remove "then"
Also where should I put this? I tested it through the website so probably you can also mention that it is the other option and manually add the KontentProjectId parameters in the URL.

2022-11-29 08:48 UTC, IvanKiral commented on sample-app-android/README.md
> +If you want to then use the Appetize you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to use unpublished content) like this:
if you `want` to see unpublished content, I guess

2022-11-29 11:13 UTC, Simply007 commented on sample-app-android/README.md
> +If you want to then use the Appetize you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to use unpublished content) like this:
```suggestion
If you want to then use the Appetize you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to see unpublished content) like this:
```

2022-11-29 11:14 UTC, Simply007 commented on sample-app-android/README.md
> +If you want to then use the Appetize you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to use unpublished content) like this:
```suggestion
If you want to use Appetize, you can create an Appetize iframe and provide `KontentProjectId` (and `KontentPreviewApiKey` if you what to use unpublished content) like this:
```

2022-12-01 09:25 UTC, IvanKiral approved these changes

2022-12-01 09:37 UTC, merged